// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type TestFilterInput struct {
	A *int `json:"a,omitempty"`
	B int  `json:"b"`
}

type TestInput struct {
	Filter *TestFilterInput `json:"filter,omitempty"`
}

type TestResult struct {
	A *int `json:"a,omitempty"`
	B int  `json:"b"`
}
